# Generated by Django 4.1.5 on 2023-02-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxiBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupied", models.BooleanField()),
                ("capacity", models.PositiveIntegerField()),
                ("number", models.PositiveIntegerField()),
                ("fare", models.FloatField()),
                ("taxi_type", models.TextField()),
                ("taxi_number", models.IntegerField()),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
